### ISSUE TITLE
Feedback from SmartCat (APAC server player)

### ISSUE THREAD

**Issue by CBlueGH** [vasyahacker/tomenet-macos-installer#1]
In in-game chat, the player SmartCat, who plays on the APAC server, just wrote the following feedback on the OSX 4.9.0 client. Since I'm logged in to github anyway, I'll just forward this for him here:

When he runs the client, it will not display the server list but automatically connect him to EU, but he is actually playing on APAC.

**Comment by vasyahacker** [comment]
fixed
