### ISSUE TITLE
I noticed a potential config file bug in the DMG

### ISSUE THREAD

**Issue by CBlueGH** [vasyahacker/tomenet-macos-installer#2]
I don't have OSX so this is only me guessing from viewing the files in an editor:

It seems to me that the file run.sh might override the font specified in the .tomenetrc config file with "16x22tg", causing the .tomenetrc font to be ignored and always be set to "16x22tg" even if the user sets a different font in the TomeNET config file ".tomenetrc", so the user cannot change fonts.

If I'm wrong, please ignore this.

**Comment by vasyahacker** [comment]
yes, you are right, but if you remove the font definition from the run script, the user will not see the TG fonts
I don't know how to do it right

1) already exists: the build script asks the user if he wants TG fonts
2) add instructions on how to change fonts in TomeNET.app/Contents/MacOS/run.sh
3) open a dialog box at startup with the question: "Use TG fonts?" and if the user answers no then use the standard ~/.tomenet to determine the font

which option is better?

**Comment by CBlueGH** [comment]
I'm not sure how OSX DMG file works.
Doesn't the TomeNET client just show all fonts if the user does  = f l   or  = f  and then browses through fonts with + and - keys until he finds one that he wants to use? If that works I think it's ok.

**Comment by vasyahacker** [comment]
yes, it works
I can turn off font presets and let the user customize
but then there is a chance that the user does not know about beautiful fonts 
anyway, I will do as you say

**Comment by CBlueGH** [comment]
Ohh ok. Hm. Well, is it maybe possible that the user gets asked one time (first time he runs the game) for font choice, and this gets written to mainwindow font name in .rc file?
For example on Linux (I don't really know OSX :/) it could be done with
a) copying one of 2 pre-made .rc files to become .tomenetrc (one with standard font, one with tg font)
b) use 'sed' command to replace the fontname string in .tomenetrc (but requires 'sed' to be available).

**Comment by vasyahacker** [comment]
ok
i did like this:
at the first start, if there is no ~/.tomenerc then it is created with default settings
then a dialog box with a choice of default font or TG (every time)
